questions = [("You are approached by a frenzied Vault scientist,  who yells, \"I'm going to put my quantum harmonizer in your photonic resonation chamber!\" What's your response?", 
"But doctor,  wouldn't that cause a parabolic destabilization of the fission singularity?", 
"Yeah? Up yours too,  buddy!", 
"Say nothing,  grab a nearby pipe and hit the scientist in the head to knock him out.  For all you knew,  he was planning to blow up the vault.", 
"Say nothing,  but slip away before the scientist can continue his rant."),

("While working as an intern in the clinic,  a patient with a strange infection on his foot stumbles through the door.  The infection is spreading at an alarming rate,  but the doctor has stepped out for a while.  What do you do?",
"Amputate the foot before the infection spreads.", 
"Scream for help.",
"Medicate the infected area to the best of your abilities.",
"Restrain the patient,  and merely observe as the infection spreads."),

("You discover a young boy lost in the lower levels of the vault.  He's frightened and hungry,  but also appears to be in possession of stolen property.  What do you do?",
"Give the boy a hug and tell him everything will be ok.",
"Confiscate the property by force,  and leave him there as punishment.",
"Pick the boy's pocket to take the stolen property for yourself,  and leave the boy to his fate.",
"Lead the boy to safety,  Then turn him over to the Overseer."),

("Congratulations!  You made one of the vault 101 baseball teams!  Which position do you prefer?", 
"Pitcher.",
"Catcher.",
"Designated Hitter.",
"None,  you wish the vault had a soccer team."),

("Your Grandmother invites you to tea,  but you're surprised when she gives you a pistol and orders you to kill another vault resident.  What do you do?",
"Obey your elder and kill the vault resident with the pistol.",
"Offer your most prized possession in exchange for the vault resident's life.",
"Ask for a minigun instead.  After all,  you don't want to miss.",
"Throw your tea in granny's face."),

("Old Mr.  Abernathy has locked himself in his quarters again,  and you've been ordered to get him out.  How do you proceed?",
"Use a bobby pin to pick the lock on the door.",
"Trade a vault hoodlum for his cherry bomb and blow open the lock.",
"Go to the armory,  retrieve a laser pistol,  and blow the lock off.",
"Just walk away and let the old coot rot."),

("Oh no!  You've been exposed to radiation,  and a mutated hand has grown out of your stomach!  Whats the best course of treatment?",
"Bullet to the brain.",
"Large Doses of anti-mutagen agent.",
"Prayer,  Maybe God will spare you in exchange for a life of pious devotion?",
"Removal of the mutated tissue with a precision laser."),

("A fellow Vault 101 resident is in possession of a Grognak the Barbarian comic book, issue number 1.  You want it.  Whats the best way to obtain it?",
"Trade the comic book for one of your own valuable possessions.",
"Steal the comic book at gunpoint.",
"Sneak into the resident's quarters,  and steal the comic book from his desk.",
"Slip some knock out drops into the resident's Nuka Cola,  and take the comic book when he's unconscious."),

("You decide it would be fun to play a prank on your father.  You enter his private restroom when no one is looking,  and...",
"Loosen some bolts on the sink.  When the sink is turned on,  the room will flood",
"Put a firecracker in the toilet.  That's sure to cause some chaos.",
"Break into the locked medicine cabinet and replace his high blood pressure medication with sugar pills.",
"Manipulate the power wattage on his razor,  so he'll get an electric shock next time he uses it."),

("Who is indisputably the most important person in Vault 101: He who shelters us from the harshness of the atomic wasteland,  and to whom we owe everything we have including our lives?",
"The Overseer.",
"The Overseer.",
"The Overseer.",
"The Overseer."),
]