import sys 
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel
from PyQt5.QtGui import QPixmap
from PyQt5.uic import loadUi
from goatQuestions import questions
from goatCareers import Careers
import time
import random


class Goat(QMainWindow):
    def __init__(self):
        super().__init__()
        self.startScreen()

    # The screen that user's see when they first open the application.
    def startScreen(self):
        loadUi("Goat-start-screen.ui", self)
        self.questionCount = 0
        self.answers = []
        self.start.clicked.connect(self.loadQuestion)
        self.vaultBoy = QPixmap('img/VaultBoy_.png')
        self.image1.setPixmap(self.vaultBoy)
        self.image1.resize(self.vaultBoy.width(), self.vaultBoy.height())

    # This function is responsible for loading questions for the GUI. They are loaded in sequential order. 
    # 'time.sleep(.5)' gives a slight pause between each question.
    def loadQuestion(self):
        time.sleep(.5)
        self.questionCount += 1
        loadUi("Goat-question-screen.ui", self)
        question_ = questions[(self.questionCount - 1)]
        self.question.setText(question_[0])
        self.answer1.setText(question_[1])
        self.answer2.setText(question_[2])
        self.answer3.setText(question_[3])
        self.answer4.setText(question_[4])
        self.questionNumber.setText(f"Question {self.questionCount}")

        self.question.setWordWrap(True)
        self.answer1.setWordWrap(True)
        self.answer2.setWordWrap(True)
        self.answer3.setWordWrap(True)
        self.answer4.setWordWrap(True)

        # Functions for each question, along with the skill being saved for each answer. Each skill is associated with certain vault jobs. At the end of the exam, a collection of all the skills are taken into account when a job is assigned
        if self.questionCount == 1:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Science'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Speech'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Melee'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Sneak'))

        elif self.questionCount == 2:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Melee'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Speech'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Medicine'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Science'))

        elif self.questionCount == 3:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Speech'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Unarmed'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Sneak'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Nothing'))

        elif self.questionCount == 4:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Explosives'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Big guns'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Melee'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Unarmed'))

        elif self.questionCount == 5:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Small guns'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Barter'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Big guns'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Explosives'))

        elif self.questionCount == 6:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Lock pick'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Explosives'))
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Barter'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Energy weapons'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Repair'))

        elif self.questionCount == 7:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Small guns'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Medicine'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Barter'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Energy weapons'))

        elif self.questionCount == 8:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Barter'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Small guns'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Sneak'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Medicine'))

        elif self.questionCount == 9:
            self.answer1_.clicked.connect(self.loadQuestion)
            self.answer1_.clicked.connect(lambda: self.saveAnswer('Repair'))

            self.answer2_.clicked.connect(self.loadQuestion)
            self.answer2_.clicked.connect(lambda: self.saveAnswer('Explosives'))

            self.answer3_.clicked.connect(self.loadQuestion)
            self.answer3_.clicked.connect(lambda: self.saveAnswer('Medicine'))


            self.answer4_.clicked.connect(self.loadQuestion)
            self.answer4_.clicked.connect(lambda: self.saveAnswer('Lock pick'))

        elif self.questionCount == 10:
            self.answer1_.clicked.connect(self.endScreen)
            self.answer2_.clicked.connect(self.endScreen)
            self.answer3_.clicked.connect(self.endScreen)
            self.answer4_.clicked.connect(self.endScreen)

    # Saving each skill that is associated with answers, to the list
    def saveAnswer(self, skill):
        self.answers.append(str(skill))
        print(self.answers)

    # End screen that shows the job they are assigned depending on the skills that were appended to the list.
    def endScreen(self):
        loadUi('Goat-end-screen.ui', self)
        chaplain = QPixmap('img/vault_chaplain3.webp')
        laundry = QPixmap('img/laundry2.webp')
        pedicurist = QPixmap('img/pedicurist3.png')
        waste = QPixmap('img/waste3.png')
        inspector = QPixmap('img/inspector.png')
        test = QPixmap('img/test3.png')
        cook = QPixmap('img/cook2.png')
        technician = QPixmap('img/technician.png')
        programmer = QPixmap('img/programmer2.png')
        tattoo = QPixmap('img/tattoo.png')
        supervisor = QPixmap('img/supervisor2.png')
        counselor = QPixmap('img/counselor.png')
        baseball = QPixmap('img/littleleague.png')
        masseuse = QPixmap('img/Masseuse.png')
        self.description.setWordWrap(True)
        self.career.setWordWrap(True)
        self.playAgainButton.clicked.connect(self.startScreen)

        # Each job with a description, skill points, and a unique image.
        if self.answers.count('Barter') == 4:
            self.image2.setPixmap(chaplain)
            self.image2.resize(chaplain.width(), chaplain.height())
            career_ = Careers['Vault Chaplain']
            self.career.setText(str('Vault Chaplan'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.barterStat.setText(str(random.randint(55, 90)))
            self.speechStat.setText(str(random.randint(55, 90)))
            self.sneakStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(random.randint(0,5)))
            self.perceptionStat.setText(str(6))
            self.enduranceStat.setText(str(7))
            self.charismaStat.setText(str(8))
            self.intelligenceStat.setText(str(random.randint(0,5)))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(7))
        
        elif self.answers.count('Big guns') == 2:
            self.image2.setPixmap(laundry)
            self.image2.resize(laundry.width(), laundry.height())
            career_ = Careers['Laundry Cannon Operator']
            self.career.setText(str('Laundry Cannon Operator'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(55, 90)))
            self.explosivesStat.setText(str(random.randint(55, 90)))
            self.repairStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(random.randint(0,5)))
            self.perceptionStat.setText(str(6))
            self.enduranceStat.setText(str(7))
            self.charismaStat.setText(str(random.randint(0,5)))
            self.intelligenceStat.setText(str(7))
            self.agilityStat.setText(str(6))
            self.luckStat.setText(str(random.randint(0,5)))

        elif self.answers.count('Energy weapons') == 2:
            self.image2.setPixmap(pedicurist)
            self.image2.resize(pedicurist.width(), pedicurist.height())
            career_ = Careers['Pedicurist']
            self.career.setText(str('Pedicurist'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(55, 90)))
            self.unarmedStat.setText(str(random.randint(55, 90)))
            self.medicineStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(6))
            self.perceptionStat.setText(str(7))
            self.enduranceStat.setText(str(random.randint(0,5)))
            self.charismaStat.setText(str(random.randint(0,5)))
            self.intelligenceStat.setText(str(random.randint(0,5)))
            self.agilityStat.setText(str(7))
            self.luckStat.setText(str(7))

        elif self.answers.count('Explosives') == 4:
            self.image2.setPixmap(waste)
            self.image2.resize(waste.width(), waste.height())
            career_ = Careers['Waste Management Specialist']
            self.career.setText(str('Waste Management Specialist'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(55, 90)))
            self.repairStat.setText(str(random.randint(55, 90)))
            self.meleeWeaponsStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(8))
            self.perceptionStat.setText(str(6))
            self.enduranceStat.setText(str(6))
            self.charismaStat.setText(str(random.randint(0,5)))
            self.intelligenceStat.setText(str(random.randint(0,5)))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(8))

        elif self.answers.count('Lock pick') == 2:
            self.image2.setPixmap(inspector)
            self.image2.resize(inspector.width(), inspector.height())
            career_ = Careers['Vault Loyalty Inspector']
            self.career.setText(str('Vault Loyalty Inspector'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(55, 90)))
            self.sneakStat.setText(str(random.randint(55, 90)))
            self.speechStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(random.randint(0,5)))
            self.perceptionStat.setText(str(6))
            self.enduranceStat.setText(str(6))
            self.charismaStat.setText(str(9))
            self.intelligenceStat.setText(str(6))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(random.randint(0,5)))

        elif self.answers.count('Medicine') == 4:
            self.image2.setPixmap(test)
            self.image2.resize(test.width(), test.height())
            career_ = Careers['Clinical Test Subject']
            self.career.setText(str('Clinical Test Subject'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(55, 90)))
            self.scienceStat.setText(str(random.randint(55, 90)))
            self.unarmedStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(random.randint(0,5)))
            self.perceptionStat.setText(str(6))
            self.enduranceStat.setText(str(8))
            self.charismaStat.setText(str(random.randint(0,5)))
            self.intelligenceStat.setText(str(7))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(6))

        elif self.answers.count('Melee') == 3:
            self.image2.setPixmap(cook)
            self.image2.resize(cook.width(), cook.height())
            career_ = Careers['Fry Cook']
            self.career.setText(str('Fry Cook'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(55, 90)))
            self.explosivesStat.setText(str(random.randint(55, 90)))
            self.repairStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(random.randint(0,5)))
            self.perceptionStat.setText(str(7))
            self.enduranceStat.setText(str(6))
            self.charismaStat.setText(str(6))
            self.intelligenceStat.setText(str(random.randint(0,5)))
            self.agilityStat.setText(str(7))
            self.luckStat.setText(str(random.randint(0,5)))

        elif self.answers.count('Repair') == 2:
            self.image2.setPixmap(technician)
            self.image2.resize(technician.width(), technician.height())
            career_ = Careers['Jukebox Technician']
            self.career.setText(str('Jukebox Technician'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(55, 90)))
            self.smallGunsStat.setText(str(random.randint(55, 90)))
            self.scienceStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(random.randint(0,5)))
            self.perceptionStat.setText(str(8))
            self.enduranceStat.setText(str(random.randint(0,5)))
            self.charismaStat.setText(str(random.randint(0,5)))
            self.intelligenceStat.setText(str(8))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(7))

        elif self.answers.count('Science') == 2:
            self.image2.setPixmap(programmer)
            self.image2.resize(programmer.width(), programmer.height())
            career_ = Careers['Pip-boy Programmer']
            self.career.setText(str('Pip-boy Programmer'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(55, 90)))
            self.energyWeaponsStat.setText(str(random.randint(55, 90)))
            self.scienceStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(random.randint(0,5)))
            self.perceptionStat.setText(str(6))
            self.enduranceStat.setText(str(6))
            self.charismaStat.setText(str(6))
            self.intelligenceStat.setText(str(9))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(random.randint(0,5)))

        elif self.answers.count('Small guns') == 3:
            self.image2.setPixmap(tattoo)
            self.image2.resize(tattoo.width(), tattoo.height())
            career_ = Careers['Tattoo Artist']
            self.career.setText(str('Tattoo Artist'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(55, 90)))
            self.speechStat.setText(str(random.randint(55, 90)))
            self.energyWeaponsStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(6))
            self.perceptionStat.setText(str(9))
            self.enduranceStat.setText(str(random.randint(0,5)))
            self.charismaStat.setText(str(7))
            self.intelligenceStat.setText(str(random.randint(0,5)))
            self.agilityStat.setText(str(5))
            self.luckStat.setText(str(random.randint(0,5)))

        elif self.answers.count('Sneak') == 3:
            self.image2.setPixmap(supervisor)
            self.image2.resize(supervisor.width(), supervisor.height())
            career_ = Careers['Shift Supervisor']
            self.career.setText(str('Shift Supervisor'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(55, 90)))
            self.speechStat.setText(str(random.randint(55, 90)))
            self.barterStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(6))
            self.perceptionStat.setText(str(6))
            self.enduranceStat.setText(str(6))
            self.charismaStat.setText(str(8))
            self.intelligenceStat.setText(str(random.randint(0,5)))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(random.randint(0,5)))

        elif self.answers.count('Speech') == 3:
            self.image2.setPixmap(counselor)
            self.image2.resize(counselor.width(), counselor.height())
            career_ = Careers['Marriage Counselor']
            self.career.setText(str('Marriage Counselor'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(55, 90)))
            self.speechStat.setText(str(random.randint(55, 90)))
            self.lockPickStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(6))
            self.perceptionStat.setText(str(random.randint(0,5)))
            self.enduranceStat.setText(str(random.randint(0,5)))
            self.charismaStat.setText(str(8))
            self.intelligenceStat.setText(str(6))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(7))

        elif self.answers.count('Unarmed') == 2 and self.answers.count('Sneak') < 2:
            self.image2.setPixmap(baseball)
            self.image2.resize(baseball.width(), baseball.height())
            career_ = Careers['Little League Coach']
            self.career.setText(str('Little League Coach'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(55, 90)))
            self.unarmedStat.setText(str(random.randint(55, 90)))
            self.speechStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(7))
            self.perceptionStat.setText(str(7))
            self.enduranceStat.setText(str(random.randint(0,5)))
            self.charismaStat.setText(str(random.randint(0,5)))
            self.intelligenceStat.setText(str(6))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(6))

        elif self.answers.count('Unarmed') == 2 and self.answers.count('Sneak') == 2:
            self.image2.setPixmap(masseuse)
            self.image2.resize(masseuse.width(), masseuse.height())
            career_ = Careers['Masseuse']
            self.career.setText(str('Masseuse'))
            self.barterStat.setText(str(random.randint(1, 55)))
            self.bigGunsStat.setText(str(random.randint(1, 55)))
            self.energyWeaponsStat.setText(str(random.randint(1, 55)))
            self.explosivesStat.setText(str(random.randint(1, 55)))
            self.lockPickStat.setText(str(random.randint(1, 55)))
            self.medicineStat.setText(str(random.randint(1, 55)))
            self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
            self.repairStat.setText(str(random.randint(1, 55)))
            self.scienceStat.setText(str(random.randint(1, 55)))
            self.smallGunsStat.setText(str(random.randint(1, 55)))
            self.sneakStat.setText(str(random.randint(1, 55)))
            self.speechStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(1, 55)))
            self.unarmedStat.setText(str(random.randint(55, 90)))
            self.medicineStat.setText(str(random.randint(55, 90)))
            self.speechStat.setText(str(random.randint(55, 90)))
            self.description.setText(str(career_[-1]))
            self.strengthStat.setText(str(7))
            self.perceptionStat.setText(str(7))
            self.enduranceStat.setText(str(6))
            self.charismaStat.setText(str(6))
            self.intelligenceStat.setText(str(random.randint(0,5)))
            self.agilityStat.setText(str(random.randint(0,5)))
            self.luckStat.setText(str(random.randint(0,5)))

        # If the skills appended to the list is non-conclusive, then a random job is selected for the vault dweller. These function will not be used very often as the list will determine a job most of the time.
        else:
            key = random.randint(0, 15)
            if key <= 1:
                self.image2.setPixmap(chaplain)
                self.image2.resize(chaplain.width(), chaplain.height())
                career_ = Careers['Vault Chaplain']
                self.career.setText(str('Vault Chaplan'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.barterStat.setText(str(random.randint(55, 90)))
                self.speechStat.setText(str(random.randint(55, 90)))
                self.sneakStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(random.randint(0,5)))
                self.perceptionStat.setText(str(6))
                self.enduranceStat.setText(str(7))
                self.charismaStat.setText(str(8))
                self.intelligenceStat.setText(str(random.randint(0,5)))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(7))
            
            elif key == 2:
                self.image2.setPixmap(laundry)
                self.image2.resize(laundry.width(), laundry.height())
                career_ = Careers['Laundry Cannon Operator']
                self.career.setText(str('Laundry Cannon Operator'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(55, 90)))
                self.explosivesStat.setText(str(random.randint(55, 90)))
                self.repairStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(6))
                self.perceptionStat.setText(str(random.randint(0,5)))
                self.enduranceStat.setText(str(7))
                self.charismaStat.setText(str(random.randint(0,5)))
                self.intelligenceStat.setText(str(7))
                self.agilityStat.setText(str(6))
                self.luckStat.setText(str(random.randint(0,5)))

            elif key == 3:
                self.image2.setPixmap(pedicurist)
                self.image2.resize(pedicurist.width(), pedicurist.height())
                career_ = Careers['Pedicurist']
                self.career.setText(str('Pedicurist'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(55, 90)))
                self.unarmedStat.setText(str(random.randint(55, 90)))
                self.medicineStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(6))
                self.perceptionStat.setText(str(7))
                self.enduranceStat.setText(str(random.randint(0,5)))
                self.charismaStat.setText(str(random.randint(0,5)))
                self.intelligenceStat.setText(str(random.randint(0,5)))
                self.agilityStat.setText(str(7))
                self.luckStat.setText(str(7))

            elif key == 4:
                self.image2.setPixmap(waste)
                self.image2.resize(waste.width(), waste.height())
                career_ = Careers['Waste Management Specialist']
                self.career.setText(str('Waste Management Specialist'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(55, 90)))
                self.repairStat.setText(str(random.randint(55, 90)))
                self.meleeWeaponsStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(8))
                self.perceptionStat.setText(str(6))
                self.enduranceStat.setText(str(6))
                self.charismaStat.setText(str(random.randint(0,5)))
                self.intelligenceStat.setText(str(random.randint(0,5)))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(8))

            elif key == 5:
                self.image2.setPixmap(inspector)
                self.image2.resize(inspector.width(), inspector.height())
                career_ = Careers['Vault Loyalty Inspector']
                self.career.setText(str('Vault Loyalty Inspector'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(55, 90)))
                self.sneakStat.setText(str(random.randint(55, 90)))
                self.speechStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(random.randint(0,5)))
                self.perceptionStat.setText(str(random.randint(0,5)))
                self.enduranceStat.setText(str(6))
                self.charismaStat.setText(str(9))
                self.intelligenceStat.setText(str(6))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(6))

            elif key == 6:
                self.image2.setPixmap(test)
                self.image2.resize(test.width(), test.height())
                career_ = Careers['Clinical Test Subject']
                self.career.setText(str('Clinical Test Subject'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(55, 90)))
                self.scienceStat.setText(str(random.randint(55, 90)))
                self.unarmedStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(6))
                self.perceptionStat.setText(str(6))
                self.enduranceStat.setText(str(8))
                self.charismaStat.setText(str(random.randint(0,5)))
                self.intelligenceStat.setText(str(7))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(random.randint(0,5)))

            elif key == 7:
                self.image2.setPixmap(cook)
                self.image2.resize(cook.width(), cook.height())
                career_ = Careers['Fry Cook']
                self.career.setText(str('Fry Cook'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(55, 90)))
                self.explosivesStat.setText(str(random.randint(55, 90)))
                self.repairStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(random.randint(0,5)))
                self.perceptionStat.setText(str(7))
                self.enduranceStat.setText(str(random.randint(0,5)))
                self.charismaStat.setText(str(6))
                self.intelligenceStat.setText(str(6))
                self.agilityStat.setText(str(7))
                self.luckStat.setText(str(random.randint(0,5)))

            elif key == 8:
                self.image2.setPixmap(technician)
                self.image2.resize(technician.width(), technician.height())
                career_ = Careers['Jukebox Technician']
                self.career.setText(str('Jukebox Technician'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(55, 90)))
                self.smallGunsStat.setText(str(random.randint(55, 90)))
                self.scienceStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(random.randint(0,5)))
                self.perceptionStat.setText(str(8))
                self.enduranceStat.setText(str(random.randint(0,5)))
                self.charismaStat.setText(str(random.randint(0,5)))
                self.intelligenceStat.setText(str(8))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(7))

            elif key == 9:
                self.image2.setPixmap(programmer)
                self.image2.resize(programmer.width(), programmer.height())
                career_ = Careers['Pip-boy Programmer']
                self.career.setText(str('Pip-boy Programmer'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(55, 90)))
                self.energyWeaponsStat.setText(str(random.randint(55, 90)))
                self.scienceStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(random.randint(0,5)))
                self.perceptionStat.setText(str(random.randint(0,5)))
                self.enduranceStat.setText(str(6))
                self.charismaStat.setText(str(6))
                self.intelligenceStat.setText(str(9))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(6))

            elif key == 10:
                self.image2.setPixmap(tattoo)
                self.image2.resize(tattoo.width(), tattoo.height())
                career_ = Careers['Tattoo Artist']
                self.career.setText(str('Tattoo Artist'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(55, 90)))
                self.speechStat.setText(str(random.randint(55, 90)))
                self.energyWeaponsStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(6))
                self.perceptionStat.setText(str(9))
                self.enduranceStat.setText(str(6))
                self.charismaStat.setText(str(7))
                self.intelligenceStat.setText(str(random.randint(0,5)))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(random.randint(0,5)))

            elif key == 11:
                self.image2.setPixmap(supervisor)
                self.image2.resize(supervisor.width(), supervisor.height())
                career_ = Careers['Shift Supervisor']
                self.career.setText(str('Shift Supervisor'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(55, 90)))
                self.speechStat.setText(str(random.randint(55, 90)))
                self.barterStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(6))
                self.perceptionStat.setText(str(6))
                self.enduranceStat.setText(str(random.randint(0,5)))
                self.charismaStat.setText(str(8))
                self.intelligenceStat.setText(str(random.randint(0,5)))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(6))

            elif key == 12:
                self.image2.setPixmap(counselor)
                self.image2.resize(counselor.width(), counselor.height())
                career_ = Careers['Marriage Counselor']
                self.career.setText(str('Marriage Counselor'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(55, 90)))
                self.speechStat.setText(str(random.randint(55, 90)))
                self.lockPickStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(6))
                self.perceptionStat.setText(str(random.randint(0,5)))
                self.enduranceStat.setText(str(random.randint(0,5)))
                self.charismaStat.setText(str(8))
                self.intelligenceStat.setText(str(6))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(7))

            elif key == 13:
                self.image2.setPixmap(baseball)
                self.image2.resize(baseball.width(), baseball.height())
                career_ = Careers['Little League Coach']
                self.career.setText(str('Little League Coach'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(55, 90)))
                self.unarmedStat.setText(str(random.randint(55, 90)))
                self.speechStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(7))
                self.perceptionStat.setText(str(7))
                self.enduranceStat.setText(str(random.randint(0,5)))
                self.charismaStat.setText(str(6))
                self.intelligenceStat.setText(str(random.randint(0,5)))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(6))

            elif key >= 14:
                self.image2.setPixmap(masseuse)
                self.image2.resize(masseuse.width(), masseuse.height())
                career_ = Careers['Masseuse']
                self.career.setText(str('Masseuse'))
                self.barterStat.setText(str(random.randint(1, 55)))
                self.bigGunsStat.setText(str(random.randint(1, 55)))
                self.energyWeaponsStat.setText(str(random.randint(1, 55)))
                self.explosivesStat.setText(str(random.randint(1, 55)))
                self.lockPickStat.setText(str(random.randint(1, 55)))
                self.medicineStat.setText(str(random.randint(1, 55)))
                self.meleeWeaponsStat.setText(str(random.randint(1, 55)))
                self.repairStat.setText(str(random.randint(1, 55)))
                self.scienceStat.setText(str(random.randint(1, 55)))
                self.smallGunsStat.setText(str(random.randint(1, 55)))
                self.sneakStat.setText(str(random.randint(1, 55)))
                self.speechStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(1, 55)))
                self.unarmedStat.setText(str(random.randint(55, 90)))
                self.medicineStat.setText(str(random.randint(55, 90)))
                self.speechStat.setText(str(random.randint(55, 90)))
                self.description.setText(str(career_[-1]))
                self.strengthStat.setText(str(7))
                self.perceptionStat.setText(str(7))
                self.enduranceStat.setText(str(6))
                self.charismaStat.setText(str(6))
                self.intelligenceStat.setText(str(random.randint(0,5)))
                self.agilityStat.setText(str(random.randint(0,5)))
                self.luckStat.setText(str(random.randint(0,5)))



app = QApplication(sys.argv)
goat = Goat()
goat.show()
app.exec_()